spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost/consulta_medica
    password: p123
  jpa:
    database: postgresql
    show-sql: 'false'
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://localhost:28017/consultaMedica
