server: 
  port: 8091
spring:
  application:
   name: config-server-bootcamp
  cloud:
   config:
    server:
     git:
       uri: https://github.com/paultbr/config-server-bootcamp-nttdata
       default-label: main
  profiles:
    active: git